# ─────────────────────────────────────────────────────────────────────────────
# NL Query Schema — exact columns from user_tab_columns (verified 2026-05-11)
# Tables: RM_ONT, RM_ONT_HISTORY, RM_OLT_HISTORY, RM_OLT, RM_ONT_AVAILABILITY
# ─────────────────────────────────────────────────────────────────────────────

STATIC_SCHEMA = {
    "RM_ONT": [
        ("SERIAL_NO",                    "VARCHAR2"),
        ("NAME",                         "VARCHAR2"),
        ("ONT_ID",                       "NUMBER"),
        ("ONT_IP",                       "VARCHAR2"),
        ("OLT_IP",                       "VARCHAR2"),
        ("TYPE",                         "NUMBER"),
        ("OLT_PIC_PON_ID",               "NUMBER"),
        ("LOCATION_ID",                  "NUMBER"),
        ("STATE",                        "NUMBER"),
        ("ADDITIONAL_INFO",              "VARCHAR2"),
        ("ALARM_REPORTING",              "NUMBER"),
        ("RESPONSIBILITY",               "VARCHAR2"),
        ("ASAP",                         "NUMBER"),
        ("GUI_NAME",                     "VARCHAR2"),
        ("REMARKS",                      "VARCHAR2"),
        ("TIME_STAMP",                   "DATE"),
        ("COMMISSION_DATE",              "DATE"),
        ("APP_STATUS",                   "VARCHAR2"),
        ("PHY_STATUS",                   "VARCHAR2"),
        ("TEMP_STATE",                   "NUMBER"),
        ("TEMP_STATE_TIME",              "DATE"),
        ("STATE_CHANGE_TIME",            "DATE"),
        ("MARK_FOR_DELETE",              "NUMBER"),
        ("NW_ENTRY_TIME",                "DATE"),
        ("VENDOR",                       "NUMBER"),
        ("INV_DONE",                     "NUMBER"),
        ("POINT_ASSET_CODE",             "VARCHAR2"),
        ("VERSION",                      "VARCHAR2"),
        ("POW_PACK_STATUS",              "VARCHAR2"),
        ("AES_STATUS",                   "VARCHAR2"),
        ("NMS_CONFIG_DATE",              "DATE"),
        ("OWNER",                        "VARCHAR2"),
        ("BHARATNET",                    "NUMBER"),
    ],
    "RM_ONT_HISTORY": [
        ("SERIAL_NO",                    "VARCHAR2"),
        ("NAME",                         "VARCHAR2"),
        ("ONT_ID",                       "NUMBER"),
        ("ONT_IP",                       "VARCHAR2"),
        ("OLT_IP",                       "VARCHAR2"),
        ("TYPE",                         "NUMBER"),
        ("OLT_PIC_PON_ID",               "NUMBER"),
        ("LOCATION_ID",                  "NUMBER"),
        ("STATE",                        "NUMBER"),
        ("ADDITIONAL_INFO",              "VARCHAR2"),
        ("ALARM_REPORTING",              "NUMBER"),
        ("RESPONSIBILITY",               "VARCHAR2"),
        ("ASAP",                         "NUMBER"),
        ("GUI_NAME",                     "VARCHAR2"),
        ("REMARKS",                      "VARCHAR2"),
        ("TIME_STAMP",                   "DATE"),
        ("COMMISSION_DATE",              "DATE"),
        ("APP_STATUS",                   "VARCHAR2"),
        ("PHY_STATUS",                   "VARCHAR2"),
        ("TEMP_STATE",                   "NUMBER"),
        ("TEMP_STATE_TIME",              "DATE"),
        ("STATE_CHANGE_TIME",            "DATE"),
        ("MARK_FOR_DELETE",              "NUMBER"),
        ("NW_ENTRY_TIME",                "DATE"),
        ("VENDOR",                       "NUMBER"),
        ("CCU",                          "NUMBER"),
        ("INV_DONE",                     "NUMBER"),
        ("THRESHOLD",                    "NUMBER"),
        ("POW_PACK_STATUS",              "VARCHAR2"),
        ("AES_STATUS",                   "VARCHAR2"),
        ("SPV",                          "NUMBER"),
        ("MARK_FOR_MAINTENANCE",         "NUMBER"),
        ("VERSION",                      "VARCHAR2"),
        ("NMS_CONFIG_DATE",              "DATE"),
        ("POINT_ASSET_CODE",             "VARCHAR2"),
    ],
    "RM_OLT": [
        ("ID",                           "NUMBER"),
        ("NAME",                         "VARCHAR2"),
        ("IP",                           "VARCHAR2"),   # NOTE: IP not IP_ADDRESS
        ("TYPE",                         "NUMBER"),
        ("LOCATION_ID",                  "NUMBER"),
        ("EMS_ID",                       "NUMBER"),
        ("ADDITIONAL_INFO",              "VARCHAR2"),
        ("RESPONSIBILITY",               "VARCHAR2"),
        ("STATE",                        "NUMBER"),
        ("COMMU_STATE",                  "VARCHAR2"),
        ("SYNC_STATE",                   "NUMBER"),
        ("ASAP",                         "NUMBER"),
        ("ALARM_REPORTING",              "NUMBER"),
        ("GUI_NAME",                     "VARCHAR2"),
        ("REMARKS",                      "VARCHAR2"),
        ("COMMISSION_DATE",              "DATE"),
        ("TIME_STAMP",                   "DATE"),
        ("STATE_CHANGE_TIME",            "DATE"),
        ("MARK_FOR_DELETE",              "NUMBER"),
        ("NW_ENTRY_TIME",                "DATE"),
        ("HSTATUS",                      "NUMBER"),
        ("HSTATUS_CHANGE_TIME",          "DATE"),
        ("VENDOR",                       "NUMBER"),
        ("INV_DONE",                     "NUMBER"),
        ("POINT_ASSET_CODE",             "VARCHAR2"),
        ("VERSION",                      "VARCHAR2"),
        ("NMS_CONFIG_DATE",              "DATE"),
        ("EMS_CONN_TYPE",                "VARCHAR2"),
        ("EMS_VLAN_ID",                  "VARCHAR2"),
        ("OWNER",                        "VARCHAR2"),
    ],
    "RM_OLT_HISTORY": [
        ("ID",                           "NUMBER"),
        ("NAME",                         "VARCHAR2"),
        ("IP",                           "VARCHAR2"),   # NOTE: IP not IP_ADDRESS
        ("TYPE",                         "NUMBER"),
        ("LOCATION_ID",                  "NUMBER"),
        ("EMS_ID",                       "NUMBER"),
        ("ADDITIONAL_INFO",              "VARCHAR2"),
        ("RESPONSIBILITY",               "VARCHAR2"),
        ("STATE",                        "NUMBER"),
        ("COMMU_STATE",                  "VARCHAR2"),
        ("SYNC_STATE",                   "NUMBER"),
        ("ASAP",                         "NUMBER"),
        ("ALARM_REPORTING",              "NUMBER"),
        ("GUI_NAME",                     "VARCHAR2"),
        ("REMARKS",                      "VARCHAR2"),
        ("COMMISSION_DATE",              "DATE"),
        ("TIME_STAMP",                   "DATE"),
        ("STATE_CHANGE_TIME",            "DATE"),
        ("MARK_FOR_DELETE",              "NUMBER"),
        ("NW_ENTRY_TIME",                "DATE"),
        ("HSTATUS",                      "NUMBER"),
        ("HSTATUS_CHANGE_TIME",          "DATE"),
        ("VENDOR",                       "NUMBER"),
        ("INV_DONE",                     "NUMBER"),
        ("VERSION",                      "VARCHAR2"),
        ("POINT_ASSET_CODE",             "VARCHAR2"),
        ("NMS_CONFIG_DATE",              "DATE"),
        ("EMS_CONN_TYPE",                "VARCHAR2"),
        ("EMS_VLAN_ID",                  "VARCHAR2"),
        ("OWNER",                        "VARCHAR2"),
    ],
    "RM_ONT_AVAILABILITY": [
        ("ONT_SERIAL_NO",                "VARCHAR2"),
        ("DOWN_TIME",                    "DATE"),
        ("UP_TIME",                      "DATE"),
        ("REMARKS",                      "VARCHAR2"),
        ("TIME_STAMP",                   "DATE"),
    ],
}

# Canonical aliases used in generated SQL
TABLE_ALIASES = {
    "RM_ONT":              "o",
    "RM_ONT_HISTORY":      "h",
    "RM_OLT":              "olt",
    "RM_OLT_HISTORY":      "olth",
    "RM_ONT_AVAILABILITY": "av",
}

TABLE_DESCRIPTIONS = {
    "RM_ONT":              "Current ONT device info, status and state",
    "RM_ONT_HISTORY":      "Historical ONT state changes and snapshots",
    "RM_OLT":              "Current OLT device info and state (IP column = OLT IP address)",
    "RM_OLT_HISTORY":      "Historical OLT device state changes (IP column = OLT IP address)",
    "RM_ONT_AVAILABILITY": "ONT availability records (up/down time, outage windows)",
}

# Cross-table join definitions
JOIN_MAP = [
    {
        "from_table": "RM_ONT",
        "from_col":   "SERIAL_NO",
        "to_table":   "RM_ONT_AVAILABILITY",
        "to_col":     "ONT_SERIAL_NO",
        "keywords":   ["availability", "uptime", "downtime", "outage", "sla"],
    },
    {
        "from_table": "RM_ONT",
        "from_col":   "OLT_IP",
        "to_table":   "RM_OLT",
        "to_col":     "IP",
        "keywords":   ["olt name", "olt info", "olt details"],
    },
]

# ── backward-compat exports ───────────────────────────────────────────────────
PRIMARY_TABLES  = list(STATIC_SCHEMA.keys())
JOINABLE_TABLES = []